apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-statusboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statusboard
  template:
    metadata:
      labels:
        app: statusboard
    spec:
      containers:
      - name: backend
        image: teemu/statusboard-backend:latest
        ports:
        - containerPort: 5000
      - name: frontend
        image: teemu/statusboard-frontend:latest
        ports:
        - containerPort: 3000
